name: Blockchain CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Linting the code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      # - name: Run ESLint for JavaScript files
      #   run: npx eslint . --ext .js,.jsx,.ts,.tsx

      # - name: Run Solhint for Solidity files
      #   run: npx solhint "contracts/**/*.sol"

  test:
    name: Running Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./Todo-List-BlockChain

      - name: Set up Ethereum environment
        run: |
          npm install -g truffle ganache-cli
          ganache-cli --deterministic &

      - name: Deploy contracts and run tests
        run: |
          truffle compile
          truffle migrate --network development
          truffle test --network development

  # build:
  #   name: Build the Application
  #   runs-on: ubuntu-latest
  #   needs: test

  #   steps:
  #     - name: Checkout the code
  #       uses: actions/checkout@v3

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Build the React app
  #       run: npm run build

  # deploy:
  #   name: Deploy the Application
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Checkout the code
  #       uses: actions/checkout@v3

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Build the React app
  #       run: npm run build

  #     - name: Deploy to GitHub Pages
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./build

  #     - name: Deploy Smart Contract to Sepolia
  #       env:
  #         ALCHEMY_API_URL: "https://eth-sepolia.g.alchemy.com/v2/VWr7R2lE8m7t2DGRFQY82bQHwp_VSnst"
  #         WALLET_PRIVATE_KEY: "44a0694b7fdc90ce225d206101b39becba86b56dca38dc7310422dae456499b9"
  #       run: |
  #         truffle compile
  #         truffle migrate --network sepolia
